**<h1 align = "center"> Pandas Basics-I </h1>**

### Pandas:
- Open source library built-on numpy library.
- Used to store, organize, clean, analyze and manipulate tabular data.

#### 1. Series (1-Dimensional)
- A Series is like a single column in Excel.
#### 2. DataFrame (2-Dimensional)
- A DataFrame is a complete table.

In [2]:
# import pandas library
import pandas as pd

In [3]:
# load dataset file
df = pd.read_csv("data.csv")

In [4]:
# display first 5 rows of the dataset
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [5]:
# display last 5 rows of the dataset
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [6]:
# display random sample of 5 rows from the dataset
df.sample(10)

    Duration          Date  Pulse  Maxpulse  Calories
13        60  '2020/12/13'    106       128     345.3
26        60      20201226    100       120     250.0
8         30  '2020/12/09'    109       133     195.1
2         60  '2020/12/03'    103       135     340.0
28        60  '2020/12/28'    103       132       NaN
25        60  '2020/12/25'    102       126     334.5
24        45  '2020/12/24'    105       132     246.0
14        60  '2020/12/14'    104       132     379.3
22        45           NaN    100       119     282.0
30        60  '2020/12/30'    102       129     380.3

In [7]:
# display the shape of the dataset (rows, columns)
df.shape

(32, 5)

In [8]:
# dispaly specific columns from the dataset
df[["Pulse", "Maxpulse"]].head()

   Pulse  Maxpulse
0    110       130
1    117       145
2    103       135
3    109       175
4    117       148

In [9]:
# type of the dataset
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [10]:
# data type of Pulse and Calories columns
df[["Pulse", "Calories"]].dtypes

Pulse         int64
Calories    float64
dtype: object

In [11]:
# type of the Pulse column
type(df.Pulse)

pandas.Series

In [12]:
# minimum and maximum values of the Pulse column
print("Minimum Pulse:", df.Pulse.min())
print("Maximum Pulse:", df.Pulse.max())

Minimum Pulse: 90
Maximum Pulse: 130

In [13]:
# filter pulse values eqaual to 100
df[df.Pulse == 100]

    Duration          Date  Pulse  Maxpulse  Calories
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
17        60  '2020/12/17'    100       120     300.0
22        45           NaN    100       119     282.0
26        60      20201226    100       120     250.0
29        60  '2020/12/29'    100       132     280.0