**<h1 align = "center"> Handling Data Files in Pandas </h1>**
- Rename cols
- Handle large dataset (rows)
- Replace with NaN values
- Create new cols
- Call custom code

In [19]:
# import library
import pandas as pd
import numpy as np
# load dataset and rename cols with updates header and maxi 5 rows from dataset
df = pd.read_csv("ecommerce_sales_data.csv", nrows = 10,
                 names = ["Year", "Month", "Product_Name", "Region", "Units_Sold", "Revenue",
                          "Profit", "Rating", "Ad_Cost"], 
                 header = 1
                          )

In [20]:
df

,Year,Month,Product_Name,Region,Units_Sold,Revenue,Profit,Rating,Ad_Cost
0,2021,October,Fashion,South,95,14081.40,3457.23,3.5,-1.00
1,2022,February,Groceries,Not Available,182,13700.50,3985.61,3.4,1929.31
2,2020,April,N.A,South,419,-1.00,20726.68,2.8,3706.92
3,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07
4,2021,March,Home Decor,North,127,999999.00,1581.60,2.8,3412.09
5,2020,December,Home Decor,North,190,6439.93,1767.44,2.3,799.25
6,2021,September,Groceries,North,124,5850.86,1739.79,1.6,560.17
7,2022,December,Books,East,93,2786.24,756.29,1.9,1089.83
8,2023,February,Books,West,43,7338.19,1452.80,2.2,2668.78
9,2021,April,Fashion,West,354,6720.94,1747.56,1.4,1422.65

### Replace with NaN values

In [21]:
# Replace with NaN values
df.replace(["N.A", "Not Available", -1.00, 999999.00], np.nan, inplace = True)

,Year,Month,Product_Name,Region,Units_Sold,Revenue,Profit,Rating,Ad_Cost
0,2021,October,Fashion,South,95,14081.40,3457.23,3.5,NaN
1,2022,February,Groceries,NaN,182,13700.50,3985.61,3.4,1929.31
2,2020,April,NaN,South,419,NaN,20726.68,2.8,3706.92
3,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07
4,2021,March,Home Decor,North,127,NaN,1581.60,2.8,3412.09
5,2020,December,Home Decor,North,190,6439.93,1767.44,2.3,799.25
6,2021,September,Groceries,North,124,5850.86,1739.79,1.6,560.17
7,2022,December,Books,East,93,2786.24,756.29,1.9,1089.83
8,2023,February,Books,West,43,7338.19,1452.80,2.2,2668.78
9,2021,April,Fashion,West,354,6720.94,1747.56,1.4,1422.65

### Create New Col

In [25]:
# create new cols
df["Tax"] = df["Revenue"] * 0.10
df.head()

,Year,Month,Product_Name,Region,Units_Sold,Revenue,Profit,Rating,Ad_Cost,Tax
0,2021,October,Fashion,South,95,14081.40,3457.23,3.5,NaN,1408.140
1,2022,February,Groceries,NaN,182,13700.50,3985.61,3.4,1929.31,1370.050
2,2020,April,NaN,South,419,NaN,20726.68,2.8,3706.92,NaN
3,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07,5181.041
4,2021,March,Home Decor,North,127,NaN,1581.60,2.8,3412.09,NaN

### Save as csv

In [26]:
# save csv file 
df.to_csv("data_tax.csv", index = False)